[PI-6] Create endpoints to food
matikaa/restaurant-backend pull request #8
Opened 2023-08-25 21:47 UTC by matikaa

2023-08-26 16:35 UTC, matikaa commented on src/main/java/com/restaurant/app/food/repository/FoodJpaRepository.java
> +public interface FoodJpaRepository extends JpaRepository<FoodEntity, Long> {
empty

2023-08-26 16:36 UTC, matikaa commented on src/main/java/com/restaurant/app/food/repository/JpaWrappedFoodRepository.java
> +    public Optional<FoodModel> update(FoodModel foodModel){
space {

2023-08-26 16:36 UTC, matikaa commented on src/main/java/com/restaurant/app/food/service/BaseFoodService.java
> +    public List<Food> getFoodByCategoryId(Long categoryId){
empty before { and also below

2023-08-27 18:41 UTC, MarcinFrejnagel requested changes

2023-08-27 18:41 UTC, MarcinFrejnagel commented on src/main/java/com/restaurant/app/category/service/CategoryService.java
>  }
empty line after }

2023-08-27 18:41 UTC, MarcinFrejnagel commented on src/main/java/com/restaurant/app/category/service/CategoryServiceMapper.java
>  }
empty line after }

2023-08-27 18:41 UTC, MarcinFrejnagel commented on src/main/java/com/restaurant/app/food/controller/FoodControllerMapper.java
> +}
empty line after }

2023-08-27 18:41 UTC, MarcinFrejnagel commented on src/main/java/com/restaurant/app/food/controller/dto/FoodListResponse.java
> +}
empty line after }

2023-08-27 18:47 UTC, MarcinFrejnagel approved these changes

2023-08-27 18:48 UTC, merged